### ISSUE TITLE
Check correct amount of parameters are passed to each function before sending call/transaction

### ISSUE THREAD

**Issue by sjkelleyjr** [trufflesuite/truffle-deployer#1]
When you pass an invalid number of constructor parameters to the deployer.deploy() method, nothing bad happens, so you assume the contract is functioning fine and it's been deployed.  Is there any way to fix this or at least detect it and throw a warning message? I poked around the truffle-deployer and truffle-contract code for a bit but nothing stuck out.  I had trouble accessing the contract constructor in any way to check the number of arguments it expected.  Could anyone point me in a direction for that?  I'd like to at least make the fix locally and wouldn't mind pushing the changes to a repo as well if it's something someone would like included.

**Comment by tcoulter** [comment]
- [ ] See how it currently fails when sending an invalid number of parameters in the constructor

Note: This should be done in `truffle-contract`.

**Comment by cgewecke** [comment]
This has been fixed for while. Thanks for opening :) Closing for housekeeping.
