### ISSUE TITLE
Improvement proposal: save deployment tx hash too

### ISSUE THREAD

**Issue by xavierlepretre** [trufflesuite/truffle-deployer#16]
The deployer already saves the deployed address.

It would be beneficial to also save the transaction hash in which the contract was deployed. The immediate benefit would be to know at which block we can start watching for events.

**Comment by self-reality** [comment]
...and get deployment gas usage as well.

**Comment by cgewecke** [comment]
This was added a while ago. Thanks for suggesting. Closing for housekeeping. 

@porobov Gas usage reporting is being added in Truffle 5, for release this summer. There's also a third-party tool called [eth-gas-reporter](https://www.npmjs.com/package/eth-gas-reporter) that plugs into truffle's tests and is useful for modeling gas consumption, although it requires that you simulate your deployments in unit-test form.
