### ISSUE TITLE
Return contract instance following `deploy`?

### ISSUE THREAD

**Issue by graemecode** [trufflesuite/truffle-deployer#21]
Wouldn't it be ideal to return the instance post deploy? E.g.:

```
deployer.deploy(MyContract).then((contractInstance) => {
  /*
    Now I have access to the instance immediately, rather than
    needing to call MyContract.deployed();
  */
})
```

Seems like it would be a quick fix following:
https://github.com/trufflesuite/truffle-deployer/blob/6cee23ae626cc38ffae78d41e3b85135c8e5dd3c/src/actions/deploy.js#L38

**Comment by graemecode** [comment]
I see that there is already a PR for this: https://github.com/trufflesuite/truffle-deployer/pull/12

Can we get that merged?

**Comment by cgewecke** [comment]
Fixed, thanks!
